// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzArena_API.Models;

#nullable disable

namespace PizzArena_API.Migrations
{
    [DbContext(typeof(PizzArenadbContext))]
    [Migration("20251122203220_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PizzArena_API.Models.Termek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ar")
                        .HasColumnType("int");

                    b.Property<int>("Kategoria_Id")
                        .HasColumnType("int");

                    b.Property<string>("Kep_Url")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModIdo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("RegIdo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("termekek");
                });
#pragma warning restore 612, 618
        }
    }
}
