// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzArena_API.Models;

#nullable disable

namespace PizzArena_API.Migrations
{
    [DbContext(typeof(PizzArenadbContext))]
    [Migration("20251201214637_FiokEsSzerepkor")]
    partial class FiokEsSzerepkor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PizzArena_API.Models.Fiok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Felhasznalonev")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("RegisztracioIdeje")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SzerepkorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SzerepkorId");

                    b.ToTable("Fiokok");
                });

            modelBuilder.Entity("PizzArena_API.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("kategoriak");
                });

            modelBuilder.Entity("PizzArena_API.Models.Szerepkor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Szerepkorok");
                });

            modelBuilder.Entity("PizzArena_API.Models.Termek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ar")
                        .HasColumnType("int");

                    b.Property<int>("Kategoria_Id")
                        .HasColumnType("int");

                    b.Property<string>("Kep_Url")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModIdo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("RegIdo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Kategoria_Id");

                    b.ToTable("termekek");
                });

            modelBuilder.Entity("PizzArena_API.Models.Fiok", b =>
                {
                    b.HasOne("PizzArena_API.Models.Szerepkor", "Szerepkor")
                        .WithMany("Fiokok")
                        .HasForeignKey("SzerepkorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szerepkor");
                });

            modelBuilder.Entity("PizzArena_API.Models.Termek", b =>
                {
                    b.HasOne("PizzArena_API.Models.Kategoria", "Kategoria")
                        .WithMany("Termekek")
                        .HasForeignKey("Kategoria_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("PizzArena_API.Models.Kategoria", b =>
                {
                    b.Navigation("Termekek");
                });

            modelBuilder.Entity("PizzArena_API.Models.Szerepkor", b =>
                {
                    b.Navigation("Fiokok");
                });
#pragma warning restore 612, 618
        }
    }
}
